### ISSUE TITLE
Sugiro colocar FIGMA

### ISSUE THREAD

**Issue by rodrigovieiraa** [vini-barbo/LeilaoCavalo#4]
Boa tarde,

Seguem os links dos layouts para o site:

https://www.figma.com/file/kpYbzIGiNrnfr1xdkaxOCv/Leil%C3%A3o-de-cavalos-(Copy)?type=design&node-id=0-1&mode=design&t=XKR3GvuurmqmSJU1-0

https://www.figma.com/file/cBnwtT7nWle2rUTyXv7lCv/leilao-cavalo?type=design&node-id=0-1&mode=design&t=W716prjwHMfvC7Tc-0

[Leilão de cavalos (Copy).zip](https://github.com/vini-barbo/LeilaoCavalo/files/12330008/Leilao.de.cavalos.Copy.zip)
[Leilão de cavalos (Copy).zip](https://github.com/vini-barbo/LeilaoCavalo/files/12330009/Leilao.de.cavalos.Copy.zip)
[leilao cavalo.zip](https://github.com/vini-barbo/LeilaoCavalo/files/12330010/leilao.cavalo.zip)

**Comment by angelgag** [comment]
Adicionado na documentação
